clear all

load ms_0_35_0_bal_2 av*
av_macro_stress_22_sq=av_stress_macro(2,:);
clear av_s* fiel* x* 

load ms_hex_35_bal_2 av*
av_macro_stress_22_hex=av_stress_macro(2,:);
clear av_s* fiel* x* 

load ms_0_50_146_bal_2 av*
av_macro_stress_22_sq_50=av_stress_macro(2,:);
clear av_s* fiel* x* 

load ms_hex_50_bal_2 av* loa*
av_macro_stress_22_hex_50=av_stress_macro(2,:);
clear av_s* fiel* x* 

% load ms_hex_35_second_bal_2
% av_macro_stress_22_hex_sec=av_stress_macro(2,:);
% clear av_s* fiel* x* 

fig1=figure; plot(100*load_array, av_macro_stress_22_sq,'rs', 100*load_array, av_macro_stress_22_hex,'b^', 100*load_array, av_macro_stress_22_sq_50,'rs', 100*load_array, av_macro_stress_22_hex_50,'b^','markersize',6,'linewidth',1.0);
% figure; plot(100*load_array, av_macro_stress_22_sq,'ko', 100*load_array, av_macro_stress_22_hex_sec,'rs', 100*load_array, av_macro_stress_22_hex,'b^');
xlim([0 0.75]);
ylim([0 800]);
axis('square'); 
ylabel('\bf{\sigma_{22} (MPa)}', 'fontsize', 16);
xlabel('\bf{\epsilon_{22} (%) }', 'fontsize', 16);
% title('\bf{Boron/Aluminum}', 'fontsize', 14);
% title('\bf{Boron/Aluminum (\mu_f= 0.35)}', 'fontsize', 14);
% H=legend('\bf{Square Packed}','\bf{Hexagonal Packed}');
% H=legend('\bf{Square Packed}','\bf{Hexagonal Packed RUC_1}','\bf{Hexagonal Packed RUC_2}');
% set(H,'box','off','fontsize',14);

legend1 = legend(...
  gca,{'\bf{Square Packed}','\bf{Hexagonal Packed}'},...
  'FontName','Arial',...
  'FontSize',14,...
  'FontWeight','bold',...
  'Location','SouthEast');
set(legend1,'box','off');

%% Create textarrow
annotation1 = annotation(...
  fig1,'textarrow',...
  [0.5 0.6],[0.7 0.7],...
  'HeadWidth',8,...
  'HeadLength',8,...
  'String',{'\bf{\upsilon_f = 0.5 }'},...
  'FontName','Arial',...
  'FontSize',16,...
  'FontWeight','bold');
 
annotation1 = annotation(...
  fig1,'textarrow',...
  [0.6 0.6],[0.4 0.5],...
  'HeadWidth',8,...
  'HeadLength',8,...
  'String',{'\bf{\upsilon_f = 0.35 }'},...
  'FontName','Arial',...
  'FontSize',16,...
  'FontWeight','bold');
 
